### PR TITLE
Replaced NuGet Sitecore packages with local dll's copy

### PR DESCRIPTION
**Pull request by KayeeNL**
Hi Jakob,

I saw that the default Rocks used the NuGet packages restore. But creating those Nuget packages, is too complicated for just simply checking out the sourcecode and build the solution.

Replaced NuGet Sitecore packages with local setup (copying the dll's into the lib folder), which works way better to setup the Sitecore Rocks solution locally, and doesn't need to make new devs create NuGet packages with the following name: SC.Lucene.Net.8.1.0.151207\lib\*

This way we don't check in the dll's from Sitecore and have an easier way of getting up to speed on extending Sitecore Rocks

--Robbert

### CODE REVIEW

**Comment by JakobChristensen** [comment]
Hey Robbert

I agree that it is not an ideal solution, but it is a trade-off.

The reason that I chose using NuGet packages is because it works with AppVeyor. AppVeyor can have a private NuGet feedback, which means that I can upload Sitecore.Kernel without breaking the Sitecore license - this is what Seam Holmesby showed at Sugcon 2016.

Having a /lib folder with assemblies, means that AppVeyor will not work.

Generating the NuGet packages is not that difficult if you use SIM (latest version) - it can automatically generate all the packages, and all you have to do is configure a NuGet repository once in Visual Studio. 

I could provide some .nuspec files and a .bat file to generate the packages, if you don't use SIM, to makes things easier.

So, what do you want - AppVeyor or easy building?

**Comment by KayeeNL** [comment]
Hi @JakobChristensen ,

Haven't had the time to look at it before. Just found out about the way to be able to generate Sitecore NuGet packages with SIM, didn't know that feature. Nice.

But what about the generated version names of the NuGet packages, should we then just decide to currently for locally setting up this repo and have it run a sucessfull build to currently just only use the 8.1.0.151207 NuGet packages, or shall we already upgrade to 160519 (which is Update-3) and update the NuGet package reference. Woudn't it be smart to make it an extra (manual) step to rename the NuGet generated packages to SC.Lucene.Net, without the version number, in that way, people can just use any Sitecore 8.1 version...

Or do you currently have specific NuGet packages in the package directory in AppVeyor?

I could adjust it and change the readme file in case you want me to.

--Robbert

**Comment by KayeeNL** [comment]
This pull request can be closed, let me know what you want to do about the specific versions of the packages

--Robbert

**Comment by KayeeNL** [comment]
@JakobChristensen ,

Just to let you know, installed a local instance of 8.1 Update -1 the 151207 version, and used the Generate Nuget packages with SIM, and the compilation works. I will create a video, where I explain this process, so it can be added to the Contributing.md file and people can get involved...

I might ask Alen Pelin to add a NuGet option in SIM, (checkbox or so), to generate NuGet file names without the version number.

--Robbert

**Comment by KayeeNL** [comment]
I think this pull request must be closed, so it doesn't end up in github.

--Robbert

**Comment by JakobChristensen** [comment]
OK - I take it that we go with SIM NuGet packages generator and AppVeyor.

I will close the Pull Request,

**Comment by KayeeNL** [comment]
@JakobChristensen ,

Would it be okay, if we will update the Sitecore Rocks nuget packages to update 3? Guess you need to do that first in AppVeyor.

Robbert

**Pull request closed without merging**
